# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys, --indent, "2"]
        exclude: (package|config).json
        files: .*\.json
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: prettier
        name: prettier
        language: system
        files: ^library/
        entry: bash -c 'cd frontend && npm run prettier'
        exclude: "node_modules"
        stages: [commit, push, manual]
    -   id: eslint
        name: eslint
        language: system
        files: ^library/
        entry: bash -c 'cd frontend && npm run lint:js'
        stages: [commit, push, manual]
